version: "3.9"

services:
  db:
    image: postgres:17
    container_name: prod-db-postgres
    env_file:
      - ./.env.production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.production
    container_name: prod-backend
    env_file:
      - ./.env.production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data_prod:
    name: prod-db-data

