version: "3.9"

services:
  db:
    image: postgres:17
    container_name: prod-db-postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    container_name: prod-backend
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8002"
    volumes:
      - ./backend/logs/prod:/app/logs
    restart: unless-stopped
 
 # Nginx service builds the frontend and serves it
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
    container_name: prod-frontend-nginx
    ports:
      - "80:80" # Exposes the app on http://localhost:8080
    depends_on:
      - backend # Ensures backend starts before nginx
    restart: unless-stopped

volumes:
  postgres_data_prod:
    name: prod-db-data

